@startuml
!include .\\.\Simulator\Controller.puml
!include .\\.\Simulator\Program.puml
!include .\\Forms\SimForm.puml
!include .\\Forms\SimForm.Designer.puml
!include .\\Model\Airport.puml
!include .\\Model\Boarding.puml
!include .\\Model\Client.puml
!include .\\Model\ClientCargo.puml
!include .\\Model\ClientFire.puml
!include .\\Model\ClientPassenger.puml
!include .\\Model\ClientRecon.puml
!include .\\Model\ClientRescue.puml
!include .\\Model\ClientSupport.puml
!include .\\Model\ClientSupportFactory.puml
!include .\\Model\ClientTransport.puml
!include .\\Model\ClientTransportFactory.puml
!include .\\Model\Deboarding.puml
!include .\\Model\Flying.puml
!include .\\Model\FlyingFire.puml
!include .\\Model\FlyingRecon.puml
!include .\\Model\FlyingRescue.puml
!include .\\Model\FlyingSupport.puml
!include .\\Model\FlyingTransport.puml
!include .\\Model\Maintenance.puml
!include .\\Model\Plane.puml
!include .\\Model\PlaneCargo.puml
!include .\\Model\PlaneFactory.puml
!include .\\Model\PlaneFire.puml
!include .\\Model\PlanePassenger.puml
!include .\\Model\PlaneRecon.puml
!include .\\Model\PlaneRescue.puml
!include .\\Model\PlaneSupport.puml
!include .\\Model\PlaneTransport.puml
!include .\\Model\Position.puml
!include .\\Model\Scenario.puml
!include .\\Model\State.puml
!include .\\Model\Waiting.puml
!include .\\Properties\Resources.Designer.puml
!include .\\obj\Debug\net7.0-windows\.NETCoreApp,Version=v7.0.AssemblyAttributes.puml
!include .\\obj\Debug\net7.0-windows\Simulator.AssemblyInfo.puml
!include .\\obj\Debug\net7.0-windows\Simulator.GlobalUsings.g.puml
@enduml
