@startuml
class ClientCargo {
    + WeightInTons : double <<get>> <<set>>
    + ClientCargo(destination:Airport)
    + ClientCargo(destination:Airport, weightInTons:double)
    + <<override>> Split(size:double) : ClientCargo
    + <<override>> ToString() : String
}
ClientTransport <|-- ClientCargo
@enduml
