@startuml
class ClientSupportFactory {
    - {static} _instance : ClientSupportFactory?
    + {static} Instance : ClientSupportFactory <<get>>
    - <<readonly>> _size : Position
    - <<readonly>> _random : Random
    - ClientSupportFactory()
    + CreateClientSupport(type:string) : ClientSupport
}
@enduml
