@startuml
class ClientPassenger {
    + NbPassenger : int <<get>> <<set>>
    + ClientPassenger(destination:Airport)
    + ClientPassenger(destination:Airport, nbPassenger:int)
    + <<override>> Split(size:double) : ClientTransport
    + <<override>> ToString() : String
}
ClientTransport <|-- ClientPassenger
@enduml
