@startuml
class FlyingRescue {
    - _handler : Step
    + FlyingRescue(plane:Plane, start:Position, client:ClientRescue)
    - Toward() : void
    - Back() : void
    + <<override>> TimeStep() : void
}
FlyingSupport <|-- FlyingRescue
@enduml
