@startuml
class FlyingFire {
    - _client : ClientFire
    - _handler : Step
    + FlyingFire(plane:Plane, start:Position, client:ClientFire)
    - Toward() : void
    - Back() : void
    + <<override>> TimeStep() : void
}
FlyingSupport <|-- FlyingFire
@enduml
