@startuml
abstract class Plane {
    + State : State <<get>> <<set>>
    # _name : string
    + Name : string <<get>> <<set>>
    # _speed : int
    + Speed : int <<get>> <<set>>
    # _maintenanceTime : int
    + MaintenanceTime : int <<get>> <<set>>
    # Plane()
    + Airport : Airport? <<get>> <<set>>
    + Plane(name:string, speed:int, maintenanceTime:int, airport:Airport)
    + GetSchema() : XmlSchema?
    + ReadXml(reader:XmlReader) : void
    + <<override>> ToString() : string?
    + {abstract} GetPossibleClients() : List<Client>
    + TimeStep() : void
    + {abstract} StartFlightProcess(client:Client) : void
}
@enduml
