@startuml
abstract class PlaneTransport {
    - _boardingTime : int
    + BoardingTime : int <<get>> <<set>>
    - _unboardTime : int
    + UnboardTime : int <<get>> <<set>>
    # PlaneTransport()
    + Capacity : int <<get>> <<set>>
    + PlaneTransport(name:string, x:int, y:int, speed:int, maintenanceTime:int, airport:Airport, boardingTime:int, unboardTime:int)
    + <<override>> ToString() : string?
}
Plane <|-- PlaneTransport
@enduml
