@startuml
class Position {
    - _x : int
    + X : int <<get>> <<set>>
    - _y : int
    + Y : int <<get>> <<set>>
    + Position(x:int, y:int)
    - Position()
    + GetSchema() : XmlSchema?
    + ReadXml(reader:XmlReader) : void
    + WriteXml(writer:XmlWriter) : void
}
IXmlSerializable <|-- Position
@enduml
