@startuml
class Scenario {
    -  <<event>> OnAirportUpdate : OnAirportUpdate 
    - _airports : List<Airport>
    + Airports : List<Airport> <<get>> <<set>>
    - _frequencyFire : int
    + FrequencyFire : int <<get>> <<set>>
    - _frequencyRecon : int
    + FrequencyRecon : int <<get>> <<set>>
    - _frequencyRescue : int
    + FrequencyRescue : int <<get>> <<set>>
    + Scenario()
    + Scenario(frequencyFire:int, frequencyRecon:int, frequencyRescue:int)
    + AddAirport(airport:Airport) : void
    + AddAirport(name:string, x:int, y:int, passengerTraffic:int, cargoTraffic:int) : void
    + EditAirport(id:int, name:string, x:int, y:int, passengerTraffic:int, cargoTraffic:int) : void
    + DeleteAirport(id:int) : void
    + AddPlane(airportId:int, name:string, type:string, speed:int, maintenanceTime:int, boardingTime:int, unboardingTime:int) : void
    + GetSchema() : XmlSchema?
    + ReadXml(reader:XmlReader) : void
    + WriteXml(writer:XmlWriter) : void
    + Save() : void
    + Load() : void
    - NotifyAirportChanged() : void
    + SubscribeAirportUpdate(updateAirports:Action<string[]>) : void
    + SubscribePlaneUpdate(updatePlanes:Action<string[]>) : void
    + GetPlanes(airportId:int) : string[]
    + GetFire() : int
    + GetRescue() : int
    + GetRecon() : int
}
IXmlSerializable <|-. Scenario
@enduml
