@startuml
class SimForm <<partial>> {
    - _controller : Controller
    - _flights : List<string>
    - _tempTime : float
    - _airports : List<string>
    + SimForm()
    - button1_Click(sender:object, e:EventArgs) : void
    - advanceTimeBtn_Click(sender:object, e:EventArgs) : void
    - mapImage_Paint(sender:object, e:PaintEventArgs) : void
    - updateMap() : void
    - getPenForType(type:string) : Pen
    + updateFlights(strings:List<string>) : void
    + updateAirports(strings:List<string>) : void
}
Form <|-- SimForm
@enduml
