@startuml
class Controller {
    - {static} _instance : Controller?
    + {static} Instance : Controller <<get>>
    -  <<event>> _emptyScenarioEvent : EmptyScenario 
    - _scenario : Scenario
    - _form : Form1
    + Form : Form1 <<get>> <<set>>
    - Controller()
    + AddPlane(airportId:int, name:string, type:string, speed:int, maintenanceTime:int, boardingTime:int, unboardingTime:int) : void
    + AddAirport(name:string, x:int, y:int, passengerTraffic:int, cargoTraffic:int) : void
    + EditAirport(airportId:int, name:string, x:int, y:int, passengerTraffic:int, cargoTraffic:int) : void
    + DeleteAirport(airportId:int) : void
    + SaveScenario() : void
    + SaveFrequencies(fire:int, rescue:int, recon:int) : void
    + LoadScenario() : void
    + EmptyScenario() : void
    + GetPlanes(airportId:int) : string[]
    + GetFire() : int
    + GetRecon() : int
    + GetRescue() : int
}
@enduml
