@startuml
rectangle controller {
!include .\\.\ScenarioGenerator\Controller.puml
}
rectangle model {
!include .\\Model\Airport.puml
!include .\\Model\Plane.puml
!include .\\Model\PlaneCargo.puml
!include .\\Model\PlaneFactory.puml
!include .\\Model\PlaneFire.puml
!include .\\Model\PlanePassenger.puml
!include .\\Model\PlaneRecon.puml
!include .\\Model\PlaneRescue.puml
!include .\\Model\PlaneSupport.puml
!include .\\Model\PlaneTransport.puml
!include .\\Model\Position.puml
!include .\\Model\Scenario.puml
Scenario "1" *-- "n" Airport
Airport "1" *-- "n" Plane
Airport "1" *-- "1" Position
Airport <-. PlaneFactory
}
rectangle view {
!include .\\.\ScenarioGenerator\Form1.puml
!include .\\.\ScenarioGenerator\Form1.Designer.puml
!include .\\View\CoordsPickerForm.puml
!include .\\View\CoordsPickerForm.Designer.puml
Form1 <-. CoordsPickerForm
}
Controller "1" *-- "1" Scenario
Controller "1" *-down- "1" Form1
@enduml
